### PR TITLE
[BREAKING CHANGE] remove stuttering in preprocessor config

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by JoelCourtney** [comment]
I agree that the original name was a mistake, but I don't think it's worth the breaking change. I'm not sure who all the users are, but the fact that anyone is using this (which is more than I ever expected) means that changing the name isn't an option. Sorry. I appreciate all your help though!

**Comment by JoelCourtney** [comment]
Yep, just to confirm my suspicions, [a quick search](https://github.com/search?q=mdbook-kroki-preprocessor&type=code) shows that this little thing I slapped together in an afternoon is being used *entirely* too many times.

**Comment by danieleades** [comment]
It would be possible to deprecate the existing name now, and then remove it after a major version bump at some point in the future

**Comment by danieleades** [comment]
> Yep, just to confirm my suspicions, [a quick search](https://github.com/search?q=mdbook-kroki-preprocessor&type=code) shows that this little thing I slapped together in an afternoon is being used *entirely* too many times.

Ha funny how that can happen. You made a good thing, kudos

**Pull request closed without merging**
